# Generated by Django 6.1 on 2026-09-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indumentaria',
            name='tipo',
            field=models.CharField(choices=[('balon', 'Balón'), ('pelota_tenis', 'Pelota de tenis'), ('pelota_ping_pong', 'Pelota de tenis de mesa'), ('raqueta', 'Raqueta'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaindumentaria',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='indumentaria',
            name='talla',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]