# Generated by Django 6.1 on 2026-09-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0002_indumentaria_tipo_reservaespacio_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaindumentaria',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
